### ISSUE TITLE
practica 3 

### ISSUE THREAD

**Issue by carlos0716c** [SistemasTecTlaxiaco/practica3-visual#1]
[practica 3 codigo.pdf](https://github.com/SistemasTecTlaxiaco/practica3-visual/files/10775235/practica.3.codigo.pdf)

**Comment by DaisyOrtiz2** [comment]
Portada(notable):falto agregar el nombre de la practica 22 puntos
Procedimiento(insuficiente):falto describir cada procedimiento 15 puntos 
Figuras ilustraciones y fotografías(insuficiente):faltaron mas imágenes 15 puntos 
Resultados y conclusiones(notable):falto el resultado  y era una conclusión por persona 22 puntos
Calificación:74/100
Porcentaje:14.8%=14%
NOTA: Esforzarse mas en la practicas que se presenten adelante

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
